begin;

drop view if exists public.thread_replies_view;
drop view if exists public.feed_timeline_view;
drop view if exists public.network_overview_view;
drop view if exists public.signals_view;

drop function if exists public.toggle_profile_follow(text);
drop function if exists public.toggle_profile_follow(text, text);
drop function if exists public.increment_post_boost(bigint);
drop function if exists public.create_dispatch(text, text, text);

create table if not exists public.profiles (
  handle text primary key,
  display_name text not null,
  bio text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.accounts (
  handle text primary key references public.profiles(handle) on delete cascade,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  author_handle text not null references public.profiles(handle) on delete cascade,
  author_name text not null,
  body text not null,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.replies (
  id bigint generated by default as identity primary key,
  thread_slug text not null references public.posts(slug) on delete cascade,
  parent_reply_id bigint null,
  author_handle text not null references public.profiles(handle) on delete cascade,
  author_name text not null,
  body text not null,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table if exists public.replies
  add column if not exists parent_reply_id bigint,
  add column if not exists likes integer not null default 0;

alter table if exists public.profiles
  drop column if exists primary_circle,
  drop column if exists followers,
  drop column if exists following;

alter table if exists public.posts
  drop column if exists circle_name,
  drop column if exists boosts,
  drop column if exists tags;

drop table if exists public.follow_relations;
drop table if exists public.circles;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'replies_parent_reply_id_fkey'
  ) then
    alter table public.replies
      add constraint replies_parent_reply_id_fkey
      foreign key (parent_reply_id) references public.replies(id) on delete cascade;
  end if;
end;
$$;

create index if not exists posts_author_handle_created_at_idx
  on public.posts (author_handle, created_at desc);

create index if not exists replies_thread_slug_created_at_idx
  on public.replies (thread_slug, created_at asc);

create index if not exists replies_parent_reply_id_idx
  on public.replies (parent_reply_id);

create or replace function public.normalize_koinonia_handle(raw text)
returns text
language sql
immutable
as $$
  select coalesce(
    nullif(
      regexp_replace(lower(ltrim(coalesce(raw, ''), '@')), '[^a-z0-9_]+', '', 'g'),
      ''
    ),
    'resident'
  );
$$;

create or replace function public.ensure_koinonia_profile(author_name text, profile_handle text)
returns void
language plpgsql
as $$
declare
  normalized_handle text := public.normalize_koinonia_handle(profile_handle);
  normalized_name text := btrim(coalesce(author_name, ''));
begin
  if normalized_name = '' then
    normalized_name := initcap(normalized_handle);
  end if;

  insert into public.profiles (handle, display_name, bio)
  values (
    normalized_handle,
    normalized_name,
    'koinonia-profile-v1:' || json_build_object(
      'description', 'Joined through the Koinonia terminal prototype.',
      'picture', E'  .--.\n /_.._\\\\\n( o  o )\n | .. |\n |____|'
    )::text
  )
  on conflict (handle) do nothing;
end;
$$;

create or replace function public.create_post(author_name text, profile_handle text, body text)
returns void
language plpgsql
as $$
declare
  normalized_handle text := public.normalize_koinonia_handle(profile_handle);
  normalized_name text := btrim(coalesce(author_name, ''));
  normalized_body text := btrim(coalesce(body, ''));
  base_slug text;
  candidate_slug text;
  suffix integer := 1;
begin
  if normalized_name = '' or normalized_body = '' then
    raise exception 'Display name and post body are required.';
  end if;

  perform public.ensure_koinonia_profile(normalized_name, normalized_handle);

  base_slug := trim(both '-' from regexp_replace(lower(left(normalized_body, 36)), '[^a-z0-9]+', '-', 'g'));
  if base_slug = '' then
    base_slug := 'post';
  end if;

  candidate_slug := base_slug;
  while exists(select 1 from public.posts where slug = candidate_slug) loop
    suffix := suffix + 1;
    candidate_slug := base_slug || '-' || suffix::text;
  end loop;

  insert into public.posts (slug, author_handle, author_name, body)
  values (
    candidate_slug,
    normalized_handle,
    normalized_name,
    normalized_body
  );
end;
$$;

create or replace function public.add_thread_reply(
  thread_slug text,
  author_name text,
  profile_handle text,
  body text,
  parent_reply_id bigint default null
)
returns void
language plpgsql
as $$
declare
  normalized_handle text := public.normalize_koinonia_handle(profile_handle);
  normalized_name text := btrim(coalesce(author_name, ''));
  normalized_body text := btrim(coalesce(body, ''));
  parent_row public.replies%rowtype;
begin
  if normalized_name = '' or normalized_body = '' then
    raise exception 'Both name and reply text are required.';
  end if;

  if not exists(select 1 from public.posts where slug = add_thread_reply.thread_slug) then
    raise exception 'Thread does not exist.';
  end if;

  perform public.ensure_koinonia_profile(normalized_name, normalized_handle);

  if add_thread_reply.parent_reply_id is not null then
    select *
    into parent_row
    from public.replies
    where id = add_thread_reply.parent_reply_id
      and public.replies.thread_slug = add_thread_reply.thread_slug;

    if not found then
      raise exception 'Reply target does not exist.';
    end if;

    if parent_row.parent_reply_id is not null then
      raise exception 'Replies can only nest one level deep.';
    end if;
  end if;

  insert into public.replies (thread_slug, parent_reply_id, author_handle, author_name, body)
  values (
    add_thread_reply.thread_slug,
    add_thread_reply.parent_reply_id,
    normalized_handle,
    normalized_name,
    normalized_body
  );
end;
$$;

create or replace function public.increment_post_like(post_id bigint)
returns void
language sql
as $$
  update public.posts
  set likes = likes + 1
  where id = increment_post_like.post_id;
$$;

create or replace function public.increment_reply_like(reply_id bigint)
returns void
language sql
as $$
  update public.replies
  set likes = likes + 1
  where id = increment_reply_like.reply_id;
$$;

create or replace view public.feed_timeline_view as
select
  p.id,
  p.slug,
  p.author_handle as handle,
  p.body,
  p.likes,
  coalesce(r.reply_count, 0)::integer as reply_count,
  p.created_at
from public.posts p
left join (
  select thread_slug, count(*)::integer as reply_count
  from public.replies
  group by thread_slug
) r on r.thread_slug = p.slug;

create or replace view public.thread_replies_view as
select
  r.id,
  r.thread_slug,
  r.parent_reply_id,
  r.author_handle as handle,
  r.body,
  r.likes,
  coalesce(children.reply_count, 0)::integer as reply_count,
  r.created_at
from public.replies r
left join (
  select parent_reply_id, count(*)::integer as reply_count
  from public.replies
  where parent_reply_id is not null
  group by parent_reply_id
) children on children.parent_reply_id = r.id;

create or replace view public.network_overview_view as
select
  (select count(*)::integer from public.posts) as posts,
  (select count(*)::integer from public.replies) as replies,
  (select count(*)::integer from public.profiles) as people;

insert into public.profiles (handle, display_name, bio)
values
  ('alina', 'Alina Forge', 'Shapes runtime identity and keeps the interface keyboard-native.'),
  ('noor', 'Noor Vale', 'Maps protocol edges, route shapes, and thread flow.'),
  ('mika', 'Mika Stone', 'Keeps deploy latency honest and the public endpoint alive.')
on conflict (handle) do update
  set display_name = excluded.display_name,
      bio = excluded.bio;

insert into public.posts (slug, author_handle, author_name, body, likes, created_at)
values
  (
    'launch-week',
    'alina',
    'Alina Forge',
    'Koinonia should feel like a real terminal town square, not a browser clone boxed into monospace.',
    18,
    now() - interval '3 hours'
  ),
  (
    'pattern-language',
    'noor',
    'Noor Vale',
    'The feed should stay readable even when threads grow, so the reply model needs a hard edge.',
    14,
    now() - interval '2 hours'
  ),
  (
    'render-path',
    'mika',
    'Mika Stone',
    'Moving the public host closer to the database removed a lot of pointless latency from the social loop.',
    11,
    now() - interval '1 hour'
  )
on conflict (slug) do update
  set author_handle = excluded.author_handle,
      author_name = excluded.author_name,
      body = excluded.body,
      likes = excluded.likes;

insert into public.replies (thread_slug, parent_reply_id, author_handle, author_name, body, likes, created_at)
select
  'launch-week',
  null,
  'noor',
  'Noor Vale',
  'Exactly. A post should feel public by default, and the thread should stay close enough to scan in one pass.',
  6,
  now() - interval '150 minutes'
where not exists (
  select 1
  from public.replies
  where thread_slug = 'launch-week'
    and parent_reply_id is null
    and author_handle = 'noor'
    and body = 'Exactly. A post should feel public by default, and the thread should stay close enough to scan in one pass.'
);

insert into public.replies (thread_slug, parent_reply_id, author_handle, author_name, body, likes, created_at)
select
  'launch-week',
  null,
  'mika',
  'Mika Stone',
  'That also keeps the deployment story simple. The runtime only has to render one public square, not a maze of channels.',
  4,
  now() - interval '140 minutes'
where not exists (
  select 1
  from public.replies
  where thread_slug = 'launch-week'
    and parent_reply_id is null
    and author_handle = 'mika'
    and body = 'That also keeps the deployment story simple. The runtime only has to render one public square, not a maze of channels.'
);

insert into public.replies (thread_slug, parent_reply_id, author_handle, author_name, body, likes, created_at)
select
  'pattern-language',
  null,
  'alina',
  'Alina Forge',
  'Agreed. Posts, replies, and reply-to-replies are enough structure for a terminal feed.',
  5,
  now() - interval '90 minutes'
where not exists (
  select 1
  from public.replies
  where thread_slug = 'pattern-language'
    and parent_reply_id is null
    and author_handle = 'alina'
    and body = 'Agreed. Posts, replies, and reply-to-replies are enough structure for a terminal feed.'
);

insert into public.replies (thread_slug, parent_reply_id, author_handle, author_name, body, likes, created_at)
select
  parent.thread_slug,
  parent.id,
  'alina',
  'Alina Forge',
  'That hard stop is what keeps the thread readable when you are moving through it line by line.',
  3,
  now() - interval '135 minutes'
from public.replies parent
where parent.thread_slug = 'launch-week'
  and parent.parent_reply_id is null
  and parent.author_handle = 'noor'
  and parent.body = 'Exactly. A post should feel public by default, and the thread should stay close enough to scan in one pass.'
  and not exists (
    select 1
    from public.replies child
    where child.parent_reply_id = parent.id
      and child.author_handle = 'alina'
      and child.body = 'That hard stop is what keeps the thread readable when you are moving through it line by line.'
  );

commit;
